server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      "force-request": true
      "force-response": true
      enabled: true

# ? ?? ??
logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework:
      security: DEBUG
      web: DEBUG
      "data.redis": DEBUG
      "web.socket": DEBUG
      messaging: DEBUG
    com.example.backend: DEBUG

# ? ??? ?? ??
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

---
# ? ?? ?? ?? ??
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://inertiamysql.mysql.database.azure.com:3306/mydb
    username: inertia
    password: tjdrhks--123
    "driver-class-name": com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      "ddl-auto": update
      naming:
        "physical-strategy": org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    "open-in-view": false
    properties:
      hibernate:
        "format_sql": true
        "show_sql": true

  data:
    redis:
      host: redis-11563.c244.us-east-1-2.ec2.redns.redis-cloud.com
      port: 11563
      password: Aj5rjRZlKtvt39genjPOqafobJZrWFKM

  # JWT ??
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    "access-token-expiration": 3600000
    "refresh-token-expiration": 604800000

  security:
    oauth2:
      client:
        registration:
          naver:
            "client-name": naver
            "client-id": DGnGVa5NDy1asU4EW6FX
            "client-secret": L_Ly2qE8uG
            "redirect-uri": http://localhost:8080/login/oauth2/code/naver
            "authorization-grant-type": authorization_code
            scope: name,email

          google:
            "client-name": google
            "client-id": 28298152408-mdd2ftib0krnraqsfpsgidsbikrecus2.apps.googleusercontent.com
            "client-secret": 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
            "redirect-uri": http://localhost:8080/login/oauth2/code/google
            "authorization-grant-type": authorization_code
            scope: profile,email

          github:
            "client-name": github
            "client-id": Ov23liPqubzegme9jqkk
            "client-secret": 9998293042c0c91eb7be8e28152da227dfdc9cfd
            "redirect-uri": http://localhost:8080/login/oauth2/code/github
            scope: read:user

        provider:
          naver:
            "authorization-uri": https://nid.naver.com/oauth2.0/authorize
            "token-uri": https://nid.naver.com/oauth2.0/token
            "user-info-uri": https://openapi.naver.com/v1/nid/me
            "user-name-attribute": response

          github:
            "authorization-uri": https://github.com/login/oauth/authorize
            "token-uri": https://github.com/login/oauth/access_token
            "user-info-uri": https://api.github.com/user

  # AWS ??
  cloud:
    aws:
      s3:
        bucket: polysprings3bucket
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        "access-key": AKIAS6J7QGFI2YJLXOZA
        "secret-key": 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

---
# ? ?? ?? ??
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://inertiamysql.mysql.database.azure.com:3306/mydb
    username: inertia
    password: tjdrhks--123
    "driver-class-name": com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      "ddl-auto": validate
      naming:
        "physical-strategy": org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    "open-in-view": false
    properties:
      hibernate:
        "format_sql": false
        "show_sql": false

  data:
    redis:
      host: redis-11563.c244.us-east-1-2.ec2.redns.redis-cloud.com
      port: 11563
      password: Aj5rjRZlKtvt39genjPOqafobJZrWFKM

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    "access-token-expiration": 3600000
    "refresh-token-expiration": 604800000

  security:
    oauth2:
      client:
        registration:
          naver:
            "client-name": naver
            "client-id": DGnGVa5NDy1asU4EW6FX
            "client-secret": L_Ly2qE8uG
            "redirect-uri": https://your-domain.com/login/oauth2/code/naver
            "authorization-grant-type": authorization_code
            scope: name,email

          google:
            "client-name": google
            "client-id": 28298152408-mdd2ftib0krnraqsfpsgidsbikrecus2.apps.googleusercontent.com
            "client-secret": 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
            "redirect-uri": https://your-domain.com/login/oauth2/code/google
            "authorization-grant-type": authorization_code
            scope: profile,email

          github:
            "client-name": github
            "client-id": Ov23liPqubzegme9jqkk
            "client-secret": 9998293042c0c91eb7be8e28152da227dfdc9cfd
            "redirect-uri": https://your-domain.com/login/oauth2/code/github
            scope: read:user

        provider:
          naver:
            "authorization-uri": https://nid.naver.com/oauth2.0/authorize
            "token-uri": https://nid.naver.com/oauth2.0/token
            "user-info-uri": https://openapi.naver.com/v1/nid/me
            "user-name-attribute": response

          github:
            "authorization-uri": https://github.com/login/oauth/authorize
            "token-uri": https://github.com/login/oauth/access_token
            "user-info-uri": https://api.github.com/user

  cloud:
    aws:
      s3:
        bucket: codinginertiaspring1
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        "access-key": AKIAS6J7QGFI2YJLXOZA
        "secret-key": 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

---
# ? Azure ?? ??
spring:
  config:
    activate:
      on-profile: azure

  datasource:
    url: jdbc:mysql://inertiamysql.mysql.database.azure.com:3306/mydb
    username: inertia
    password: tjdrhks--123
    "driver-class-name": com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      "ddl-auto": validate
      naming:
        "physical-strategy": org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    "open-in-view": false
    properties:
      hibernate:
        "format_sql": false
        "show_sql": false

  data:
    redis:
      host: redis-11563.c244.us-east-1-2.ec2.redns.redis-cloud.com
      port: 11563
      password: Aj5rjRZlKtvt39genjPOqafobJZrWFKM

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
    "access-token-expiration": 3600000
    "refresh-token-expiration": 604800000

  security:
    oauth2:
      client:
        registration:
          naver:
            "client-name": naver
            "client-id": DGnGVa5NDy1asU4EW6FX
            "client-secret": L_Ly2qE8uG
            "redirect-uri": https://inertia-app.azurewebsites.net/login/oauth2/code/naver
            "authorization-grant-type": authorization_code
            scope: name,email

          google:
            "client-name": google
            "client-id": 28298152408-mdd2ftib0krnraqsfpsgidsbikrecus2.apps.googleusercontent.com
            "client-secret": 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
            "redirect-uri": https://inertia-app.azurewebsites.net/login/oauth2/code/google
            "authorization-grant-type": authorization_code
            scope: profile,email

          github:
            "client-name": github
            "client-id": Ov23liPqubzegme9jqkk
            "client-secret": 9998293042c0c91eb7be8e28152da227dfdc9cfd
            "redirect-uri": https://inertia-app.azurewebsites.net/login/oauth2/code/github
            scope: read:user

        provider:
          naver:
            "authorization-uri": https://nid.naver.com/oauth2.0/authorize
            "token-uri": https://nid.naver.com/oauth2.0/token
            "user-info-uri": https://openapi.naver.com/v1/nid/me
            "user-name-attribute": response

          github:
            "authorization-uri": https://github.com/login/oauth/authorize
            "token-uri": https://github.com/login/oauth/access_token
            "user-info-uri": https://api.github.com/user

  cloud:
    aws:
      s3:
        bucket: codinginertiaspring1
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        "access-key": AKIAS6J7QGFI2YJLXOZA
        "secret-key": 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
